version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "80:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - client